const QUIZZES = {
  q_fundamentals: [
    {q: "What is the primary purpose of encapsulation?", opts: ["To make code run faster", "To hide internal data and restrict direct access", "To allow multiple inheritance", "To enable dynamic memory allocation"], a: 1, exp: "Encapsulation hides the internal state of an object and requires all interaction to be performed through an object's methods (getters/setters)."},
    {q: "Which keyword is used to make members accessible outside the class?", opts: ["private", "protected", "public", "extern"], a: 2, exp: "The `public` access specifier allows members to be accessed from any part of the program where the object is visible."},
    {q: "What is the default access specifier for members of a `class` in C++?", opts: ["public", "private", "protected", "None of the above"], a: 1, exp: "By default, all members of a `class` are `private`. In a `struct`, the default is `public`."},
    {q: "Which of the following describes a constructor?", opts: ["A special function used to destroy an object", "A method that always returns an integer", "A special method invoked automatically when an object is created", "A standard variable type"], a: 2, exp: "A constructor is a special member function that initializes an object of its class type. It has the same name as the class and no return type."}
  ],
  q_ptr: [
    {q: "What does the `*` operator do when applied to a pointer variable?", opts: ["Returns the memory address", "Dereferences the pointer to access the value", "Multiplies the pointer by a scalar", "Deallocates the memory"], a: 1, exp: "The `*` operator (dereference operator) accesses the value stored at the memory address the pointer holds."},
    {q: "What is a reference in C++?", opts: ["A pointer that can be reassigned", "A copy of a variable", "An alias for an existing variable", "A dynamic array"], a: 2, exp: "A reference is an alias (an alternative name) for an existing variable. It must be initialized when declared and cannot be reassigned."},
    {q: "What is the correct way to assign the address of `int a` to pointer `p`?", opts: ["int* p = a;", "int* p = *a;", "int* p = &a;", "int& p = a;"], a: 2, exp: "The `&` (address-of) operator is used to get the memory address of a variable."},
    {q: "What is the output of the following code snippet?\n\nint x = 10;\nint* ptr = &x;\n*ptr = 20;\nstd::cout << x;", opts: ["10", "20", "The memory address of x", "Compilation error"], a: 1, exp: "The pointer `ptr` stores the address of `x`. Dereferencing `ptr` (`*ptr = 20`) modifies the original value of `x`."},
    {q: "Consider the following class method:\n\nvoid MyClass::setValue(int value) {\n    this->value = value;\n}\n\nWhat does `this->value` refer to?", opts: ["The method's parameter `value`", "A global variable named `value`", "The object's member variable `value`", "A static variable `value`"], a: 2, exp: "The `this` pointer points to the current object. Using `this->value` explicitly refers to the object's member variable, disambiguating it from the method parameter `value`."},
    {q: "What is the output of the following code?\n\nint arr[] = {10, 20, 30};\nint* p = arr;\nstd::cout << *(p + 1);", opts: ["10", "11", "20", "Garbage value"], a: 2, exp: "`p` points to the first element of `arr` (10). Pointer arithmetic `p + 1` advances the pointer to the next element (20), and `*` dereferences it."}
  ],
  q_mem: [
    {q: "Which memory area is used for dynamic memory allocation?", opts: ["Stack", "Heap", "BSS segment", "Code segment"], a: 1, exp: "The Heap is used for dynamic memory allocation (using `new` or `malloc`), managed manually by the programmer."},
    {q: "What happens if you use `new` but forget to use `delete`?", opts: ["Syntax error", "Stack overflow", "Memory leak", "Segmentation fault"], a: 2, exp: "Failing to deallocate memory allocated on the heap leads to a memory leak, as the memory remains reserved even when it's no longer needed."},
    {q: "Which operator is used to deallocate an array allocated with `new[]`?", opts: ["delete", "delete[]", "free()", "dealloc"], a: 1, exp: "You must use `delete[]` to properly deallocate memory allocated for arrays using `new[]`."},
    {q: "What is the primary advantage of stack memory over heap memory?", opts: ["It is larger in size", "It is managed automatically and is faster to allocate", "It allows dynamic resizing", "It prevents memory leaks entirely"], a: 1, exp: "Stack memory is automatically managed by the compiler (variables are pushed and popped as functions are called and return) and memory allocation is generally faster than on the heap."}
  ],
  q_oop: [
    {q: "What allows a derived class to provide a specific implementation of a function already provided by its base class?", opts: ["Function overloading", "Method overriding", "Encapsulation", "Templates"], a: 1, exp: "Method overriding is when a derived class has a definition for one of the member functions of the base class. The base function must be marked `virtual`."},
    {q: "What does a pure virtual function look like?", opts: ["virtual void draw() {}", "virtual void draw() = 0;", "void draw() override;", "pure virtual void draw();"], a: 1, exp: "A pure virtual function is declared by assigning 0 in its declaration: `virtual void myFunc() = 0;`. This makes the class abstract."},
    {q: "Which concept allows you to treat objects of different classes through the same base class interface?", opts: ["Polymorphism", "Encapsulation", "Multiple Inheritance", "Operator Overloading"], a: 0, exp: "Polymorphism allows objects of different types to be treated as instances of the same class through a common base interface."},
    {q: "What is the primary role of a 'vtable' in C++?", opts: ["To store static variables", "To enable dynamic dispatch for virtual functions at runtime", "To manage dynamic memory allocation", "To track memory leaks"], a: 1, exp: "The Virtual Table (vtable) is an array of function pointers used for dynamic dispatch to resolve function calls at runtime for polymorphic classes."}
  ],
  q_advanced: [
    {q: "What are Templates used for in C++?", opts: ["Memory management", "Generic programming", "Exception handling", "File I/O"], a: 1, exp: "Templates are the foundation of generic programming, allowing you to write code (functions or classes) that works with any data type."},
    {q: "Which STL container provides fast random access but slow insertions in the middle?", opts: ["std::list", "std::map", "std::vector", "std::set"], a: 2, exp: "`std::vector` is a dynamic array, so accessing elements by index is very fast (O(1)), but inserting elements in the middle requires shifting subsequent elements (O(N))."},
    {q: "What keyword is used to signal that an exceptional condition has occurred?", opts: ["catch", "try", "throw", "raise"], a: 2, exp: "The `throw` keyword is used to throw an exception when a problem occurs, which can then be caught by a `catch` block."},
    {q: "Which STL container is best suited for storing key-value pairs sorted by key?", opts: ["std::vector", "std::unordered_map", "std::map", "std::list"], a: 2, exp: "`std::map` stores key-value pairs in a sorted order (usually implemented as a red-black tree), whereas `std::unordered_map` does not maintain any order."}
  ],
  q_mix: [
    {q: "What is the `this` pointer?", opts: ["A pointer to the base class", "A pointer to the object itself", "A pointer to the vtable", "A smart pointer"], a: 1, exp: "The `this` pointer is a hidden pointer passed to non-static member functions, pointing to the object on which the function was called."},
    {q: "Why should destructors be virtual in base classes?", opts: ["To speed up object destruction", "To prevent memory leaks when deleting derived objects through base pointers", "It is required for encapsulation", "To allow destructor overloading"], a: 1, exp: "If a base class destructor is not virtual, deleting a derived object via a base pointer only calls the base destructor, leaking any resources managed by the derived class."},
    {q: "What does `std::unique_ptr` guarantee?", opts: ["Shared ownership", "Exclusive ownership", "Garbage collection", "Faster execution"], a: 1, exp: "`std::unique_ptr` provides strict exclusive ownership. Only one `unique_ptr` can point to the resource, and it is automatically deleted when the pointer goes out of scope."}
  ],
  q_snippets: [
    {q: "What is the output of the following code?\n\nint main() {\n    int a = 5;\n    int& b = a;\n    b = 10;\n    std::cout << a;\n    return 0;\n}", opts: ["5", "10", "Compilation error", "Undefined behavior"], a: 1, exp: "`b` is a reference to `a`. Changing `b` to 10 changes `a` to 10."},
    {q: "Consider the following class:\n\nclass Test {\npublic:\n    Test() { std::cout << \"A\"; }\n    ~Test() { std::cout << \"B\"; }\n};\n\nint main() {\n    Test* t = new Test();\n    return 0;\n}\n\nWhat is the output?", opts: ["AB", "A", "B", "No output"], a: 1, exp: "The constructor is called, printing 'A'. However, `delete t;` is missing, so the destructor is never called, causing a memory leak and printing only 'A'."},
    {q: "What does this code output?\n\nclass Base {\npublic:\n    virtual void show() { std::cout << \"Base\"; }\n};\nclass Derived : public Base {\npublic:\n    void show() { std::cout << \"Derived\"; }\n};\n\nint main() {\n    Base* b = new Derived();\n    b->show();\n    delete b;\n    return 0;\n}", opts: ["Base", "Derived", "BaseDerived", "Compilation error"], a: 1, exp: "Since `show()` is `virtual`, C++ uses runtime polymorphism to call `Derived::show()`, which prints 'Derived'."},
    {q: "What is the output?\n\nint main() {\n    int arr[3] = {10, 20, 30};\n    int* p = arr;\n    p++;\n    std::cout << *p;\n    return 0;\n}", opts: ["10", "11", "20", "30"], a: 2, exp: "`p` points to `arr[0]` (10). `p++` increments the pointer to point to the next element, `arr[1]` (20). `*p` then dereferences it to 20."},
    {q: "Evaluate the snippet:\n\ntemplate <typename T>\nT add(T a, T b) {\n    return a + b;\n}\n\nint main() {\n    std::cout << add(5, 5.5);\n    return 0;\n}", opts: ["10", "10.5", "11", "Compilation error"], a: 3, exp: "Compilation error: The compiler cannot deduce a single type for `T` because the arguments are of different types (`int` and `double`). You would need to explicitly specify the type, e.g., `add<double>(5, 5.5)`."},
    {q: "What is the output?\n\nclass Base {\npublic:\n    virtual void print(int x = 10) { std::cout << \"Base: \" << x; }\n};\nclass Derived : public Base {\npublic:\n    void print(int x = 20) override { std::cout << \"Derived: \" << x; }\n};\n\nint main() {\n    Base* b = new Derived();\n    b->print();\n    return 0;\n}", opts: ["Base: 10", "Derived: 20", "Derived: 10", "Compilation error"], a: 2, exp: "Virtual functions are dispatched dynamically at runtime, but default arguments are resolved statically at compile time based on the pointer type (`Base*`). So it calls `Derived::print` but uses `Base`'s default argument (10)."},
    {q: "What happens when this code is executed?\n\nclass Animal { public: virtual void speak() { std::cout << \"Animal\"; } };\nclass Dog : public Animal { public: void speak() override { std::cout << \"Dog\"; } };\n\nint main() {\n    Dog d;\n    Animal a = d;\n    a.speak();\n    return 0;\n}", opts: ["Dog", "Animal", "Compilation error", "Undefined behavior"], a: 1, exp: "This is 'Object Slicing'. When `d` is assigned to a value-type `Animal a`, the `Dog` specific parts (including its vtable entry for `speak`) are sliced off. `a` is purely an `Animal`, so it prints 'Animal'."},
    {q: "What is the output?\n\nint main() {\n    int arr[] = {5, 10, 15};\n    int* p = arr;\n    int val = *p++;\n    std::cout << val << \" \" << *p;\n    return 0;\n}", opts: ["10 10", "5 10", "10 15", "5 5"], a: 1, exp: "`*p++` uses postfix increment. It returns the current value pointed to by `p` (5), assigns it to `val`, and then increments the pointer `p` to point to the next element (10)."},
    {q: "What is the output?\n\nint main() {\n    int *p = new int(5);\n    int *q = p;\n    *q = 20;\n    std::cout << *p;\n    delete p;\n    return 0;\n}", opts: ["5", "20", "Compilation error", "Undefined behavior"], a: 1, exp: "`p` and `q` point to the same memory location (aliasing). Changing the value through `q` also changes the value seen through `p`."},
    {q: "What is the output?\n\nclass Base {\npublic:\n    void show() { std::cout << \"Base\"; }\n};\nclass Derived : public Base {\npublic:\n    void show() { std::cout << \"Derived\"; }\n};\n\nint main() {\n    Base *b;\n    Derived d;\n    b = &d;\n    b->show();\n    return 0;\n}", opts: ["Base", "Derived", "Compilation error", "Runtime error"], a: 0, exp: "Since `show()` is NOT declared `virtual` in the base class, early (static) binding occurs. The compiler looks at the pointer type (`Base*`) and calls `Base::show()`."},
    {q: "Consider the following code:\n\nclass A {};\nclass B : public A {};\nint main() {\n    A *p = new B();\n    return 0;\n}\n\nWhat is the static type and dynamic type of `p`?", opts: ["Static: A*, Dynamic: A*", "Static: B*, Dynamic: A*", "Static: A*, Dynamic: B*", "Static: B*, Dynamic: B*"], a: 2, exp: "The static type is declared at compile time (`A*`), while the dynamic type is the actual type of the object it points to at runtime (`B*`)."},
    {q: "What does this code output?\n\nint add(int a, int b) { return a + b; }\ndouble add(double a, double b) { return a + b; }\n\nint main() {\n    int x = 5, y = 6;\n    std::cout << add(x, y);\n    return 0;\n}", opts: ["11", "11.0", "Compilation error", "Ambiguous call"], a: 0, exp: "This is compile-time polymorphism (function overloading). The compiler perfectly matches `add(x, y)` to the `int` version since both `x` and `y` are integers, outputting 11."},
    {q: "Identify the mistake in this code:\n\nint *p = new int;\n*p = 10;\nfree(p);", opts: ["Syntax error on line 1", "Cannot assign 10 to a pointer", "Memory deallocation is incorrect", "The code is perfectly valid"], a: 2, exp: "Memory allocated with `new` must be deallocated using `delete`. `free()` is a C-library function meant to be used with `malloc()`, and mixing them leads to undefined behavior."},
    {q: "Consider the operator overloading snippet:\n\nclass Number {\n    int value;\npublic:\n    Number(int v) { value = v; }\n    Number operator+(Number n) {\n        return Number(value + n.value);\n    }\n    int getValue() { return value; }\n};\n\nint main() {\n    Number a(2), b(3);\n    Number c = a + b;\n    std::cout << c.getValue();\n    return 0;\n}", opts: ["Compilation error", "2", "3", "5"], a: 3, exp: "The `operator+` is overloaded to add the `value` of two `Number` objects and return a new `Number` object. `a + b` is internally translated to `a.operator+(b)`, returning a `Number` with value 5."},
    {q: "What is the exact output of this program?\n\nint main() {\n    int i = 25;\n    std::cout << std::hex << i << \" \";\n    std::cout << std::oct << i << \" \";\n    std::cout << std::dec << i;\n    return 0;\n}", opts: ["25 25 25", "19 31 25", "19 25 31", "Compilation error"], a: 1, exp: "The I/O manipulators change the base for integer output. 25 in hexadecimal is `19` (16*1 + 9), in octal is `31` (8*3 + 1), and in decimal is `25`."},
    {q: "Is the following code valid? Why or why not?\n\nclass Shape {\npublic:\n    virtual void draw() = 0;\n};\n\nint main() {\n    Shape s;\n    return 0;\n}", opts: ["Valid, it creates an empty Shape object", "Valid, but draw() cannot be called", "Invalid, Shape is an abstract class", "Invalid, missing constructor"], a: 2, exp: "The class `Shape` contains a pure virtual function `draw() = 0`, making it an abstract class. Abstract classes cannot be instantiated, so `Shape s;` causes a compilation error."}
  ],
  q_copyctor: [
    {q: "What does a copy constructor do?", opts: ["Allocates memory for a new object", "Initializes a new object as a copy of an existing one", "Copies only static members", "Deletes the original object"], a: 1, exp: "A copy constructor creates a new object by copying the members of an existing object. Its signature is `ClassName(const ClassName& other)`."},
    {q: "What is a 'shallow copy' problem?", opts: ["The copy is too slow", "Both objects share the same pointer, causing double-delete on destruction", "Only half the members are copied", "The copy constructor is missing a return type"], a: 1, exp: "Shallow copy copies raw pointer values, not the data they point to. Both original and copy point to the same heap memory. Deleting one invalidates the other."},
    {q: "What is the Rule of Three in C++?", opts: ["A class should have at most 3 constructors", "If you define destructor, copy constructor, or copy assignment, define all three", "A function can have at most 3 parameters", "Inheritance depth should not exceed 3"], a: 1, exp: "If any one of destructor, copy constructor, or copy assignment operator needs to be user-defined, all three should be defined, because the class manages a resource."}
  ],
  q_static: [
    {q: "What does a static member variable in a class mean?", opts: ["It cannot be modified", "It is shared across all instances of the class", "It is initialized at compile time only", "It is private by default"], a: 1, exp: "A `static` member variable belongs to the class itself, not to any individual object. All instances share the same copy."},
    {q: "How do you call a static member function?", opts: ["Only through an object", "Using ClassName::functionName()", "Using the this pointer", "Only inside the constructor"], a: 1, exp: "Static member functions can be called using the class name and scope resolution operator `::`, without creating any object instance."},
    {q: "Which of the following is true about static member functions?", opts: ["They can access non-static members directly", "They have access to the this pointer", "They cannot access non-static members directly", "They must return void"], a: 2, exp: "Static member functions have no `this` pointer, so they cannot directly access non-static data members or non-static member functions."}
  ],
  q_friend: [
    {q: "What does the `friend` keyword do in C++?", opts: ["Makes a function a member of the class", "Grants a non-member function access to private members", "Creates a copy of the class", "Inherits from another class"], a: 1, exp: "The `friend` keyword grants a non-member function or another class the ability to access private and protected members of the class."},
    {q: "Is friendship in C++ inherited?", opts: ["Yes, friends of a base class are also friends of derived classes", "No, friendship is not inherited", "Only if declared virtual", "Only for friend classes, not friend functions"], a: 1, exp: "Friendship is not inherited in C++. If class A is a friend of B, a class derived from B does NOT automatically get the same friendship."},
    {q: "Which of the following best describes when to use a friend function?", opts: ["When you want to hide member data", "When an external function needs private access, like operator overloading for streams", "When you want to override a virtual function", "When two classes share the same base"], a: 1, exp: "Friend functions are commonly used for overloading `<<` and `>>` stream operators, where the function needs access to private members but cannot be a member function."}
  ],
  q_multinh: [
    {q: "What is the Diamond Problem in C++ multiple inheritance?", opts: ["A class inherits from 4 base classes", "Ambiguity when a class inherits from two classes that both inherit from the same base", "Two classes with the same name in different namespaces", "Stack overflow due to deep inheritance"], a: 1, exp: "The Diamond Problem occurs when class D inherits from B and C, both of which inherit from A. D ends up with two copies of A, causing ambiguity."},
    {q: "How does `virtual` inheritance solve the Diamond Problem?", opts: ["By removing one of the base classes", "By ensuring only one shared copy of the common base class exists", "By making the base class abstract", "By disabling multiple inheritance"], a: 1, exp: "Virtual inheritance (`class B : virtual public A`) ensures that only one copy of the common base class A is shared in the derived class hierarchy, eliminating ambiguity."},
    {q: "What is the syntax for multiple inheritance in C++?", opts: ["class D inherits B, C", "class D : public B : public C", "class D : public B, public C", "class D extends B, C"], a: 2, exp: "Multiple inheritance uses a comma-separated list of base classes in the class declaration: `class D : public B, public C { };`"}
  ]
};
